name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{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 }}
          GIST_ID: ${{ https://gist.github.com/forwarder1121/d0e97b57ebaef0cc5d338b43382b48bd}}
          TIMEZONE: Asia/Seoul
