name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{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 }}
          GIST_ID: ${{ https://gist.github.com/forwarder1121/8b3024fcd847bb1ae0128b2c99ac4d19 }}
          TIMEZONE: Asia/Seoul
